############################################################
# Plataforma de Automação
############################################################

# Nome da plataforma
PLATFORM_NAME="Fabio Automation Server"

# Versão
PLATFORM_VERSION="1.0"

# Diretórios
AUTOMACAO_ROOT="/opt/automacao"

COMPOSE_DIR="${AUTOMACAO_ROOT}/compose"

VOLUMES_DIR="${AUTOMACAO_ROOT}/volumes"

CONFIG_DIR="${AUTOMACAO_ROOT}/configs"

SCRIPT_DIR="${AUTOMACAO_ROOT}/scripts"

LOG_DIR="${AUTOMACAO_ROOT}/logs"

DOC_DIR="${AUTOMACAO_ROOT}/documentacao"

BACKUP_SCRIPT_DIR="${AUTOMACAO_ROOT}/backup"

RESTORE_DIR="${AUTOMACAO_ROOT}/restore"

TEMP_DIR="${AUTOMACAO_ROOT}/temp"

# Disco de backup
BACKUP_DIR="/mnt/backups"

# Timezone
TIMEZONE="America/Sao_Paulo"

# Retenção de backups
RETENTION_DAYS=30

############################################################
