# =====================================================
# SAR - Servidor de Automação Residencial
# Arquivo de Identidade da Plataforma
# =====================================================

NOME="Servidor de Automação Residencial"
SIGLA="SAR"
VERSAO="0.1.0"

AUTOR="Fabio Batista"

DIRETORIO_RAIZ="/opt/automacao"
DIRETORIO_BACKUP="/mnt/backups"

SISTEMA="Linux Mint"
IDIOMA="pt_BR"
