# =====================================================

# SAR - Servidor de Automação Residencial

# Cadastro Central de Serviços

# =====================================================

# Docker

DOCKER="docker"

# Containers Docker

HOMEASSISTANT="homeassistant"
NODERED="nodered"
MOSQUITTO="mosquitto"
ESPHOME="esphome"
PORTAINER="portainer"
